-- MySQL Script generated by MySQL Workbench
-- Wed Jun 16 12:43:31 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema codigoparatodos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema codigoparatodos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `codigoparatodos` DEFAULT CHARACTER SET utf8 ;
USE `codigoparatodos` ;

-- -----------------------------------------------------
-- Table `codigoparatodos`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codigoparatodos`.`clientes` (
  `id_clientes` INT NOT NULL,
  `nome_cliente` VARCHAR(255) NOT NULL,
  `sobrenome_cliente` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `nascimento` DATE NOT NULL,
  PRIMARY KEY (`cpf`),
  UNIQUE INDEX `id_clientes_UNIQUE` (`id_clientes` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codigoparatodos`.`dividas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codigoparatodos`.`dividas` (
  `id_dividas` INT NOT NULL,
  `nome_empresa` VARCHAR(255) NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  `valor_divida` DECIMAL NOT NULL,
  `clientes_id_clientes` INT NOT NULL,
  `clientes_cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id_dividas`),
  INDEX `fk_dividas_clientes_idx` (`clientes_id_clientes` ASC, `clientes_cpf` ASC) ,
  CONSTRAINT `fk_dividas_clientes`
    FOREIGN KEY (`clientes_id_clientes` , `clientes_cpf`)
    REFERENCES `codigoparatodos`.`clientes` (`id_clientes` , `cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
