-- MySQL Script generated by MySQL Workbench
-- Thu Jun 17 12:17:27 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema codigoparatodos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema codigoparatodos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `codigoparatodos` DEFAULT CHARACTER SET utf8 ;
USE `codigoparatodos` ;

-- -----------------------------------------------------
-- Table `codigoparatodos`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codigoparatodos`.`clientes` (
  `id_clientes` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(255) NOT NULL,
  `sobrenome_cliente` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `nascimento` DATE NOT NULL,
  `salario` DECIMAL(50) NOT NULL,
  PRIMARY KEY (`cpf`),
  UNIQUE INDEX `id_clientes_UNIQUE` (`id_clientes` ASC) ,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codigoparatodos`.`dividas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codigoparatodos`.`dividas` (
  `codigo_divida` INT NOT NULL,
  `nome_empresa` VARCHAR(255) NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  `valor_divida` DECIMAL NOT NULL,
  `clientes_cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`codigo_divida`, `clientes_cpf`, `valor_divida`),
  INDEX `fk_dividas_clientes_idx` (`clientes_cpf` ASC) ,
  CONSTRAINT `fk_dividas_clientes`
    FOREIGN KEY (`clientes_cpf`)
    REFERENCES `codigoparatodos`.`clientes` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codigoparatodos`.`renegocio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codigoparatodos`.`renegocio` (
  `id_renegocio` INT NOT NULL,
  `vezes` SMALLINT(2) NOT NULL,
  `novo_valor_divida` DECIMAL(1000) NOT NULL,
  `dividas_codigo_divida` INT NOT NULL,
  `dividas_clientes_cpf` VARCHAR(11) NOT NULL,
  `dividas_valor_divida` DECIMAL NOT NULL,
  PRIMARY KEY (`id_renegocio`),
  INDEX `fk_renegocio_dividas1_idx` (`dividas_codigo_divida` ASC, `dividas_clientes_cpf` ASC, `dividas_valor_divida` ASC) ,
  CONSTRAINT `fk_renegocio_dividas1`
    FOREIGN KEY (`dividas_codigo_divida` , `dividas_clientes_cpf` , `dividas_valor_divida`)
    REFERENCES `codigoparatodos`.`dividas` (`codigo_divida` , `clientes_cpf` , `valor_divida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
