-- MySQL Script generated by MySQL Workbench
-- Sun Jun 20 20:15:09 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema codigoparatodos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema codigoparatodos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `codigoparatodos` DEFAULT CHARACTER SET utf8 ;
USE `codigoparatodos` ;

-- -----------------------------------------------------
-- Table `codigoparatodos`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codigoparatodos`.`clientes` (
  `id_clientes` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(255) NOT NULL,
  `sobrenome_cliente` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `cpf` BIGINT(11) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `nascimento` DATE NOT NULL,
  `salario` DECIMAL(7,2) NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  `nresidencia` INT NOT NULL,
  `cidade` VARCHAR(255) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(255) NOT NULL,
  `pais` VARCHAR(255) NOT NULL,
  `cep` INT NOT NULL,
  `complemento` VARCHAR(45) NOT NULL,
  `profissao` VARCHAR(255) NOT NULL,
  `sexo` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`cpf`),
  UNIQUE INDEX `id_clientes_UNIQUE` (`id_clientes` ASC) ,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codigoparatodos`.`dividas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codigoparatodos`.`dividas` (
  `codigo_divida` INT UNSIGNED NOT NULL,
  `nome_empresa` VARCHAR(255) NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  `valor_divida` DECIMAL(7,2) NOT NULL,
  `cpf` BIGINT(11) NOT NULL,
  `sitaucao` TINYINT(1) NOT NULL,
  PRIMARY KEY (`codigo_divida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codigoparatodos`.`renegocio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codigoparatodos`.`renegocio` (
  `id_renegocio` INT NOT NULL AUTO_INCREMENT,
  `vezes` INT NOT NULL,
  `novo_valor_divida` DECIMAL(7,2) NOT NULL,
  `clientes_cpf` BIGINT(11) NOT NULL,
  `valor_parcela` DECIMAL(7,2) NOT NULL,
  `dividas_codigo_divida` INT UNSIGNED NOT NULL,
  `situacao` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_renegocio`),
  INDEX `fk_renegocio_clientes1_idx` (`clientes_cpf` ASC) ,
  INDEX `fk_renegocio_dividas1_idx` (`dividas_codigo_divida` ASC) ,
  CONSTRAINT `fk_renegocio_clientes1`
    FOREIGN KEY (`clientes_cpf`)
    REFERENCES `codigoparatodos`.`clientes` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_renegocio_dividas1`
    FOREIGN KEY (`dividas_codigo_divida`)
    REFERENCES `codigoparatodos`.`dividas` (`codigo_divida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codigoparatodos`.`emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codigoparatodos`.`emprestimo` (
  `id_emprestimo` INT NOT NULL AUTO_INCREMENT,
  `valor_solicitado` DECIMAL(7,2) NOT NULL,
  `vezes` INT NOT NULL,
  `mensalidade` DECIMAL(7,2) NOT NULL,
  `data_vencimento` DATE NOT NULL,
  `clientes_cpf` BIGINT(11) NOT NULL,
  `iof` DECIMAL(7,2) NOT NULL,
  `situacao` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_emprestimo`),
  INDEX `fk_emprestimo_clientes1_idx` (`clientes_cpf` ASC) ,
  CONSTRAINT `fk_emprestimo_clientes1`
    FOREIGN KEY (`clientes_cpf`)
    REFERENCES `codigoparatodos`.`clientes` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
